### ISSUE TITLE
[TODO] Digital number unions

### ISSUE THREAD

**Issue by O5X** [shnopy/todo#3]

**Comment by O5X** [comment]
Using https://www.shutterstock.com/image-vector/calculator-digital-numbers-456060766

**Comment by O5X** [comment]
Is this an ok distance? I'll scale it down ofc https://imgur.com/a/Z06vWCx

**Comment by shnopy** [comment]
Test against the blue blob on the keypad, it can't be any taller or wider than it

**Comment by O5X** [comment]
Y position needed: 4.954

**Comment by shnopy** [comment]
Progress?

**Comment by O5X** [comment]
Will continue soon.

**Comment by shnopy** [comment]
Feature not required
