### ISSUE TITLE
[TODO] Make modlogs to show kicks, warns and bans

### ISSUE THREAD

**Issue by Greymagic27** [shnopy/todo#35]

**Comment by shnopy** [comment]
These would show up in logs anyway, not sure there's a need for a dedicated command

**Comment by Greymagic27** [comment]
A dedicated command helps us to see what happened at a glance and without having to root through loads of logs for that user.

**Comment by shnopy** [comment]
I can work on this but it likely wouldn't be done for the bot's release as it's not required for its running
