### ISSUE TITLE
[TODO] Allow panning of camera in autoshop menu

### ISSUE THREAD

**Issue by Greymagic27** [shnopy/todo#50]
Relates to #49 but you should be able to move the camera in the menu

**Comment by shnopy** [comment]
not bug, works as intended

**Comment by Greymagic27** [comment]
How will you be able to see side/front/back modifications when you're in the autoshop? Ditto with #49

**Comment by shnopy** [comment]
This will be done by having set cameras the user can switch to

**Comment by Greymagic27** [comment]
Issue now triaged as low and LTP

**Comment by shnopy** [comment]
Added
