### ISSUE TITLE
[TODO] The build

### ISSUE THREAD

**Issue by shnopy** [shnopy/todo#7]
Assigned all people to build

**Comment by shnopy** [comment]
@O5X This needs to be done asap. The quicker the build is done, the quicker we can script it

**Comment by shnopy** [comment]
Awaiting this feature before building: https://devforum.roblox.com/t/future-is-bright-phase-3-studio-beta/639903

**Comment by shnopy** [comment]
[House Image](https://cdnb.artstation.com/p/assets/images/images/000/320/005/large/david-alvarez-acu-env-villa-ext-upgrade-02.jpg?1416921678)

**Comment by shnopy** [comment]
Start of cafe in progress
[Close](https://cdn.discordapp.com/attachments/702832096820854792/743849126306775050/unknown.png)
[Far](https://cdn.discordapp.com/attachments/702832096820854792/743853016050040852/unknown.png)

**Comment by Greymagic27** [comment]
Not required
